# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Roberto@123"
      MSSQL_PID: Express
      mem_limit: "2gb"
    networks:
      - dockersql-network
    ports:
      - 1433:1433

  userapi:
    image: userapi
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - dockersql-network
    depends_on:
      - ms-sql-server
    ports:
      - 8080:80
